Vagrant.configure("2") do |config|
  config.vm.define "nginx" do |nginx|
    nginx.vm.box = "ubuntu/bionic64"
    nginx.vm.network "public_network"
    nginx.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "nginx_playbook.yml"
    end
  end

  config.vm.define "mysql" do |mysql|
    mysql.vm.box = "ubuntu/bionic64"
    mysql.vm.network "public_network"
    mysql.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "mysql_playbook.yml"
    end
  end
end
